version: '3.8'
name: custodian-infra
services:
  postgres:
    image: postgres:15
    container_name: custodian-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: custodian-db
      POSTGRES_USER: custodian
      POSTGRES_PASSWORD: custodian123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./src/main/resources/02-data.sql:/docker-entrypoint-initdb.d/02-data.sql

  redis:
    image: redis:7-alpine
    container_name: custodian-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    name: custodian-postgres-data
  redis_data:
    name: custodian-redis-data