--INSERT INTO users (name, email, password, enabled, email_verified) VALUES
--('Alice', 'alice@example.com', 'hashed_password_1', TRUE, TRUE),
--('Bob', 'bob@example.com', 'hashed_password_2', TRUE, FALSE),
--('Charlie', 'charlie@example.com', 'hashed_password_3', FALSE, FALSE);
--
--INSERT INTO roles (name, description) VALUES
--('ADMIN', 'Administrator with full access'),
--('USER', 'Regular user with limited access'),
--('MODERATOR', 'Moderator with specific privileges');
--
--
--INSERT INTO groups (name, description) VALUES
--('Engineering', 'Engineering team group'),
--('HR', 'Human Resources group'),
--('Sales', 'Sales and Marketing team group');
--
--INSERT INTO permissions (name, description) VALUES
--('READ_PRIVILEGES', 'Permission to read data'),
--('WRITE_PRIVILEGES', 'Permission to write data'),
--('DELETE_PRIVILEGES', 'Permission to delete data');
--
--INSERT INTO user_roles (user_id, role_id) VALUES
--(1, 1), -- Alice assigned ADMIN role
--(2, 2), -- Bob assigned USER role
--(2, 3); -- Bob also assigned MODERATOR role
--
--INSERT INTO group_memberships (user_id, group_id, role_id) VALUES
--(1, 1, 1), -- Alice in Engineering with ADMIN role
--(2, 2, 2), -- Bob in HR with USER role
--(3, 3, 3); -- Charlie in Sales with MODERATOR role
--
--INSERT INTO group_permissions (group_id, permission_id, expires_at) VALUES
--(1, 1, NULL), -- Engineering group granted READ_PRIVILEGES
--(1, 2, '2024-12-31'), -- Engineering group granted WRITE_PRIVILEGES until end of 2024
--(2, 1, NULL), -- HR group granted READ_PRIVILEGES
--(3, 1, NULL), -- Sales group granted READ_PRIVILEGES
--(3, 3, '2024-06-30'); -- Sales group granted DELETE_PRIVILEGES until mid-2024
--
--
---- Insert the private key
--INSERT INTO secrets (name, private_key,public_key, type, active, created_at, updated_at)
--VALUES
--    ('dashboard-private-key', '-----BEGIN PRIVATE KEY-----
--                              MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDv5RFDquukcAAJ
--                              vyMzK2tp5fidjHf+EuBJZwsB0NyuGORogbTAIgL7aQ5K7DmHI9qkgpDgrI8BJlGD
--                              nfpFHmzJkCbdh8fVjeSyP7+8e2INUJBWCE1gwk6HtTRA8yjiU1v2ugWKq48kzPyS
--                              McLNd2zRpQOpH/d2qWLC/SFMprRN6HFeArVU7nUK0/b00WGy6aYaHO6lXiU18LCs
--                              eWty82HXk4TJN7BLRm72qZ5i//Ir1oz3zZhhiC6wNzEcBGfKKJeAb1tAKe05v2QA
--                              bqnXyueXiEKhralkKP7dxZz1Chl4AKohSexs39EBBTI0ZaZuD/I+kpucUtHSTjAS
--                              Cak9a1ltAgMBAAECggEAJDqygEcsXkGh59brcHtitfQKt3Ry3LaqE7vRoD0UTuCo
--                              ghXwn8GjNKfZhjwltgCWsRic26mD0VchoWB23wBoyooQLI2ogtpyiu7wvHzfwoYD
--                              vlJzqSS/KmSV1ydB6ehP77OJSbd+Hz8r98I3GsOp9gFXS6/ttgh/x1XmNQbKHSeu
--                              NMcpX9LsVqc64sWJFFwRPhd7YZ9F0aOFwRNBKpG35m9IDmzJmxvdOgGDmF77MHfq
--                              pLhfNNhbALNC11oG2xWMiWJlQBwGYh93EA0v4ishDFVM9iRq/ZYDHrIFP5ShhyJV
--                              fkP1LybMdIH+Y1sPvp3heD+cADz3kmCkSCOGGgtv2wKBgQDymjk6fZ3X0RzzBld2
--                              8t3ABNtQGVhQC1gEfSQ9ms7uSAszRNULFbF3xPxCyh897em+rzUuAnI0Ak4ziWbO
--                              O6EAHuYIdF0ZaOY0sOSLyimLS0v0+e8+xddvMdbJfZgsFk0uh3x3vYjzJAoLFQfw
--                              2600Bl0b0FqOz1WD+yjI3b6YJwKBgQD9JJCV6MdyfopLJq7kgafwvD+nflytJHUf
--                              rtxHfn8zMP2kkI8UsM3Y5Xw5cfzRYVg1MoTjpbjN1zkKv4IJAbWgzDFnhuAY2+I+
--                              6C0RvsRqRBQ7C/lpT+iOc1luOleA1PJbjSSSISjCYvNlXu5OPG7EoXpbzzQoSLYN
--                              cDwIJwrKSwKBgA9q97oc45wkoQdc3tAjbS5X4Kw9gBxOLEDUxynXHdGM6JFQjY2P
--                              ymCHN1TzTXr9FL7WmbWb2DAv+VJTKCJxLbE5RXtCEeycewzcNRohNfSxS1l9TNQb
--                              dK6PZ0wU3Efo/uy3FZTyibKSFsVPh9qpy18kDGTJIAg1awThQF1LomI/AoGBAJB9
--                              7omi9TVFRWrgCbQkzdd7nFnepsetp60OAm5Mpg5ySFVGrmUBBn5nfyDLD6P0DIVQ
--                              8MmALpxP3R9lcLPzZdkCtLCDLCcEW3/Mxuz6FuMROPr7OsIB+pxU+xcP9iJzamMX
--                              jWhbxQgvsv6J0TyXAiL6iP0eqIbV+hRxm9KLdn1BAoGBAMwi/BRuvHtR4GBIKSRP
--                              /5gYEVAORNlWjf329U+SLXfs39i0LAmpObI7BwT0Tmc5yg4bDETtJIVcbolS/kOb
--                              QXmMe2SJd9BBNP3OsE3xG3OFFh8VLDuJ5OwAG7cD1MAdGeZABlw7kZqm/SH4po1K
--                              wXpHqsO7mNTLCoMVu0p9W5tS
--                              -----END PRIVATE KEY-----','-----BEGIN PUBLIC KEY-----
--                                                                                      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7+URQ6rrpHAACb8jMytr
--                                                                                      aeX4nYx3/hLgSWcLAdDcrhjkaIG0wCIC+2kOSuw5hyPapIKQ4KyPASZRg536RR5s
--                                                                                      yZAm3YfH1Y3ksj+/vHtiDVCQVghNYMJOh7U0QPMo4lNb9roFiquPJMz8kjHCzXds
--                                                                                      0aUDqR/3dqliwv0hTKa0TehxXgK1VO51CtP29NFhsummGhzupV4lNfCwrHlrcvNh
--                                                                                      15OEyTewS0Zu9qmeYv/yK9aM982YYYgusDcxHARnyiiXgG9bQCntOb9kAG6p18rn
--                                                                                      l4hCoa2pZCj+3cWc9QoZeACqIUnsbN/RAQUyNGWmbg/yPpKbnFLR0k4wEgmpPWtZ
--                                                                                      bQIDAQAB
--                                                                                      -----END PUBLIC KEY-----', 'RSA_PRIVATE', TRUE, NOW(), NOW());
--
--
--
--INSERT INTO oauth_clients (
--    client_id,name,application_type, client_secret, redirect_uris, grant_types, scopes, token_endpoint_auth_method, algorithm, key_id, created_at, updated_at
--)
--VALUES (
--    'iam-dashboard',
--    'iam-dashboard',
--    'web',
--    'hashed_client_secret_value',
--    '["http://localhost:8080/callback"]',
--    '["authorization_code", "refresh_token"]',
--    '["openid", "profile", "email", "admin"]',
--    'client_secret_basic',
--    'RS256',
--    (SELECT id FROM secrets WHERE name = 'dashboard-private-key'),
--    NOW(), NOW()
--);
--
